## 自定义层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self,X):
        return X -X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8,128),CenteredLayer())

In [4]:
Y = net(torch.rand(4,8))
print(Y.mean())

tensor(-4.6566e-09, grad_fn=<MeanBackward0>)


In [9]:
class MyLinear(nn.Module):
    def __init__(self,in_units,units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units,units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self,X):
        linear = torch.matmul(X,self.weight)+self.bias
        return F.relu(linear)

In [10]:
linear = MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[ 0.1289,  1.0595, -0.0529],
        [-0.4599,  0.0430, -0.2566],
        [-0.2477,  0.5530,  1.5827],
        [-0.5309,  2.7070, -0.2803],
        [ 0.4618, -1.5173,  0.0985]], requires_grad=True)

In [11]:
linear(torch.rand(2,5))

tensor([[0.0000, 0.3239, 0.0263],
        [0.0000, 1.9514, 0.6261]], grad_fn=<ReluBackward0>)

In [12]:
net = nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.rand(2,64))

tensor([[18.7534],
        [15.3867]], grad_fn=<ReluBackward0>)